version: '3'

services:
  sqs:
    image: graze/sqs-local
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/elasticmq.conf
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure

  indexer:
    build: .
    env_file: .env
    depends_on:
      - sqs
      - elasticsearch
