service: sdn-pipeline

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:*
        - dynamodb:*
        - es:*
        - s3:*
      Resource: "*"
  environment:
    S3_BUCKET: ${env:S3_BUCKET}
    S3_DATA_SOURCE: ${env:S3_DATA_SOURCE}
    DYNAMODB_CHECKSUM: ${env:DYNAMODB_CHECKSUM}
    SNS_FETCH_QUEUE: { "Ref": "SNSFetchQueue" }
    SNS_INDEX_QUEUE: { "Ref": "SNSIndexQueue" }
    ES_INDEX: ${env:ES_INDEX}
    ES_URL: ${env:ES_URL}
    MAX_SNS_MESSAGE_SIZE: ${env:MAX_SNS_MESSAGE_SIZE}

functions:
  bootstrapper:
    name: sdn-pipeline-bootstrapper
    handler: dist/bootstrapper/index.bootstrap
    timeout: 20
    events:
      - schedule: rate(7 days)
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":sdn-pipeline-bootstrap-queue"
          topicName: sdn-pipeline-bootstrap-queue
  fetcher:
    name: sdn-pipeline-fetcher
    handler: dist/fetcher/index.fetch
    timeout: 60
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":sdn-pipeline-fetch-queue"
          topicName: sdn-pipeline-fetch-queue
  indexer:
    name: sdn-pipeline-indexer
    handler: dist/indexer/index.index
    timeout: 60
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":sdn-pipeline-index-queue"
          topicName: sdn-pipeline-index-queue

resources:
  Resources:
    SNSBootstrapQueue:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "sdn-pipeline-bootstrap-queue"
    SNSFetchQueue:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "sdn-pipeline-fetch-queue"
    SNSIndexQueue:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "sdn-pipeline-index-queue"
